### ISSUE TITLE
Should delegate include the delegation root when matching selectors?

### ISSUE THREAD

**Issue by kfranqueiro** [dojo/dom#25]
*This topic originally came up on #24.*

`delegate` currently does not include the root node (i.e. the target that the delegated handler is registered on) when it attempts to match selectors.

Take the following example:

```html
<div id="foo" class="foo">foo</div>
```

```ts
delegate(document.getElementById('foo'), '.foo', 'click', function () {
    console.log('click');
});
```

Here is how various libraries behave in this case:

* `dom/delegate` WILL NOT log.
* Dojo 1 with the `acme` selector engine WILL log.
* Dojo 1 with the `lite` selector engine WILL NOT log.
  * This is what `dom/delegate`'s logic is currently based on.  And yes, Dojo 1's selector engines are apparently inconsistent on this edge case.
* jQuery WILL NOT log.
* YUI 3 WILL log.

So the question is, what's the right answer?

Personally, I can't think of a time when I've ever expected to match a selector *including* the delegation root, but that's more of an argument for this being an exceedingly edge case, not necessarily an argument in either direction.

**Comment by kitsonk** [comment]
My opinion is not logging, because I think it is surprising to have the
root of your query returned. This was a large part of why the qSA logic was
considered "broken" and generally rooted queries don't consider the root,
only descendants. It looks like in Dojo 1 this edge case wasn't found in
acme, but I suspect we would have agreed to "fix" it if someone had noticed.

**Comment by kfranqueiro** [comment]
I'm inclined to agree.  You put it in good terms - basically, that you expect queries to be performed *under* the root, not including it.

OTOH, when I asked for opinions yesterday on IRC, @neonstalwart was thinking in the other direction:

> The reasoning would be that the click is triggered on the element AND the target matches the selector.

Anyway, I will leave this open for the time being to let others think about it.

**Comment by drjayvee** [comment]
While I don't really have a preference, I don't see how including the container does any harm, so delegate might as well include it. I doubt many developers will consciously use this feature to avoid having to set up two listeners though.

Either way, it can't hurt to mention whether or not the container is included in the documentation.

**Comment by kitsonk** [comment]
> I don't see how including the container does any harm, so delegate might as well include it.

Now that we have identified the inconsistencies... I am afraid we have to explicitly choose a path.  People will become dependent on the feature in unexpected ways and any changes will cause further regressions.

**Comment by drjayvee** [comment]
I agree that the APIs should be consistent.

I would argue that ignoring the root does more harm than good, so I would be slightly in favor of including it.

**Comment by kitsonk** [comment]
> I would argue that ignoring the root does more harm than good

Why?

**Comment by dmethvin** [comment]
Maybe this is picky semantics, but if the root handles the event then it isn't delegation is it? :smile_cat: 

In practical application I am not convinced there is a reasonable use case for including the root. This probably hasn't come up in practice because either the delegation filter never matches the root (e.g., table elements handling events from child rows)  or because the root is used strictly for attaching delegated events and has no other UI function (e.g., a div used as a view container).

I can imagine situations where you might do a delegated event at the root that performs some function and stops propagation, then the root has its own handler that does some other processing on events that bubble to the root without being handled. However, IMO that would be better done as two separate event handlers.

**Comment by drjayvee** [comment]
I think it's _more likely_ devs will run into problems because they _expect_ the root to be matched than in the other case (where they _expect_ it to be ignored).

I do agree that, semantically, it's cleaner for delegation to ignore the root. I can also totally get behind @dmethvin's argument that this does not actually cause problems in practice.

I think we've picked enough nits here ;) Let's leave the code as is and document this behavior.

**Comment by bryanforbes** [comment]
IMO, the code should in `dom/delegate` should remain the way it is for the reasons that @dmethvin has outlined. I don't remember this problem ever coming up in Dojo 1 even when we had two selector engines behaving differently, so I don't think the average (or any?) users will actually hit this.

**Comment by kfranqueiro** [comment]
Okay, I've added an explicit test assertion for this and made a note to make sure we state this specifically in the README.

Thanks everyone for the comments.
