### ISSUE TITLE
Implement dom.create

### ISSUE THREAD

**Issue by eheasley** [dojo/dom#7]
- [ ] Implement and test `dom.create` as outlined in the dom proposal.
- [ ] Investigate effort to include type information for return values and possibly arguments object for string subtypes for each type of element that can be created.

[dom Proposal Reference](https://docs.google.com/document/d/1fXGrlsl3aTqst7mCj3XqlKdbuCJs4rB9r7qIxC-tWMQ/edit#heading=h.hgfhvyqi9jqk)

**Comment by kfranqueiro** [comment]
I probably should have also referenced this issue in https://github.com/dojo/dom/commit/322dbdf904f0255cdedcb9f0595e9576a7243c6d since it pertains to the 2nd item in the description.  This commit adds return types for the relevant subset of tags (minus obsolete ones) which TypeScript's own [dom.generated.d.ts](https://raw.githubusercontent.com/Microsoft/TypeScript/master/src/lib/dom.generated.d.ts) has typings for in the `createElement` signature.

I investigated potentially going further and adding support for smarter typings for the second argument based on `HTMLElement`-derived types included in TypeScript (instead of the rather fuzzy `CreateArgs`), but it seemed prohibitive for a few reasons:

* The addition of the `attributes` key would likely require us to extend each `HTMLElement`-derived interface we'd like to reuse
* `attributes` is already a thing that already exists on `Node` - we're overloading its meaning for `CreateArgs`.  You can't redefine members with incompatible types when you extend interfaces, which means we'd have to roll our own parent interface rather than base on `HTMLElement`
* `dom.generated.d.ts` has already demonstrated its fair share of bugs, so leaning heavily on its `HTMLElement`-derived types for the sake of validating properties at construction time seemed likely to be more trouble than it's worth
* Even if we did go through this effort, it would *only* validate properties, not attributes
